version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    tags:
      - netgo
    flags:
      - -trimpath
    ldflags:
      - -s -w -extldflags "-static"
archives:
  - name_template: |
      {{- .ProjectName -}}_
      {{- tolower .Os -}}_
      {{- if eq .Arch "amd64" -}}x86_64
      {{- else if eq .Arch "386" -}}i386
      {{- else -}}{{- .Arch -}}{{- end -}}
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
dockers:
  - image_templates:
      - "ghcr.io/patrickdappollonio/duality:{{ .Tag }}-amd64"
    goos: linux
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }} version {{ .Version }}. See release notes at https://github.com/patrickdappollonio/{{ .ProjectName }}/releases/tag/v{{ .RawVersion }}"
      - "--label=org.opencontainers.image.url=https://github.com/patrickdappollonio/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/patrickdappollonio/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
  - image_templates:
      - "ghcr.io/patrickdappollonio/duality:{{ .Tag }}-arm64"
    goos: linux
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.description={{ .ProjectName }} version {{ .Version }}. See release notes at https://github.com/patrickdappollonio/{{ .ProjectName }}/releases/tag/v{{ .RawVersion }}"
      - "--label=org.opencontainers.image.url=https://github.com/patrickdappollonio/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.source=https://github.com/patrickdappollonio/{{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - '--label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}'
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
docker_manifests:
  - name_template: "ghcr.io/patrickdappollonio/duality:v{{ .RawVersion }}"
    image_templates:
      - "ghcr.io/patrickdappollonio/duality:{{ .Tag }}-amd64"
      - "ghcr.io/patrickdappollonio/duality:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/patrickdappollonio/duality:v{{ .Major }}"
    image_templates:
      - "ghcr.io/patrickdappollonio/duality:{{ .Tag }}-amd64"
      - "ghcr.io/patrickdappollonio/duality:{{ .Tag }}-arm64"
  - name_template: "ghcr.io/patrickdappollonio/duality:latest"
    image_templates:
      - "ghcr.io/patrickdappollonio/duality:{{ .Tag }}-amd64"
      - "ghcr.io/patrickdappollonio/duality:{{ .Tag }}-arm64"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
  groups:
    - title: "Fixes, improvements and updates"
      order: 1
    - title: "Dependency updates"
      regexp: "^Bump .* from .* to .*$" # dependabot
      order: 999
release:
  mode: append
  footer: |
    ## Container images

    The following container images are available in `x86_64` and `arm64` architectures:

    ```
    ghcr.io/patrickdappollonio/duality:v{{ .RawVersion }}
    ghcr.io/patrickdappollonio/duality:v{{ .Major }}
    ```

    You can always pull from `ghcr.io/patrickdappollonio/duality:latest` to get the latest version, but we highly recommend you pin your versions to a specific major release, like `v{{ .Major }}`.
